Animals/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver.Core;
using System.Configuration;
using Animals.App_Start;
using Animals.Models;
using MongoDB.Driver;
using System.Web.UI.WebControls;
using MongoDB.Driver.Linq;

namespace Animals.Controllers
{
    public class AnimalsController : Controller
    {
        private AnimalsContext animalsContext;

        private IMongoCollection<AnimalsModel> animalsCollection;
        private IMongoCollection<LoginModels> loginsCollection;
        private IMongoCollection<AnimalsModel> createUserCollection;

        public AnimalsController()
        {
            animalsContext = new AnimalsContext();
            animalsCollection = animalsContext.database.GetCollection<AnimalsModel>("Animals");
        }
        // GET: Animals
        public ActionResult Index()
        {
            List<AnimalsModel> animals = animalsCollection.AsQueryable<AnimalsModel>().ToList();
            return View(animals);
        }

        // GET: Animals/Details/5
        public ActionResult Details(string id)
        {
            var animalsId = new ObjectId(id);
            var animal = animalsCollection.AsQueryable<AnimalsModel>().SingleOrDefault(x => x.Id == animalsId);
            return View(animal);
        }

        // GET: Animals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Animals/Create
        [HttpPost]
        public ActionResult Create(AnimalsModel animals)
        {
            try
            {
                // TODO: Add insert logic here

                animalsCollection.InsertOne(animals);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Animals/Edit/5
        public ActionResult Edit(string id)
        {
            var animalsId = new ObjectId(id);
            var animal = animalsCollection.AsQueryable<AnimalsModel>().SingleOrDefault(x => x.Id == animalsId);
            return View(animal);
        }

        // POST: Animals/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, AnimalsModel animals)
        {
            try
            {
                // TODO: Add update logic here
                var filter = Builders<AnimalsModel>.Filter.Eq("_id", ObjectId.Parse(id));
                var update = Builders<AnimalsModel>.Update
                    .Set("Name", animals.Name)
                    .Set("Age", animals.Age);
                var result = animalsCollection.UpdateOne(filter, update);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Animals/Delete/5
        public ActionResult Delete(string id)
        {
            var animalsId = new ObjectId(id);
            var animal = animalsCollection.AsQueryable<AnimalsModel>().SingleOrDefault(x => x.Id == animalsId);
            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, AnimalsModel animals)
        {
            try
            {
                // TODO: Add delete logic here
                animalsCollection.DeleteOne(Builders<AnimalsModel>.Filter.Eq("_id", ObjectId.Parse(id)));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        static List<LoginModels> logins = new List<LoginModels>();
        public ActionResult Record(LoginModels logins)
        {
            return View(logins);
        }
        public ActionResult Login()
        {
            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Login(string Username, string Password, LoginModels login)
        {
            if (!ModelState.IsValid)
            {
                var W = loginsCollection.AsQueryable<LoginModels>().Where(w => w.Username == Username && w.Password == Password).FirstOrDefault();
                try
                {

                    if (Username == W.Username && Password == W.Password)
                    {
                        return RedirectToAction("Index","Animals");
                    }
                    else
                    {
                        return View("Index");
                    }
                }
                catch (NullReferenceException)
                {
                    ModelState.AddModelError("", "Tài khoản hoặc mật khẩu không chính xác !");
                    return View("Login");
                }
            }
            else
            {
                ModelState.AddModelError("", "Tài khoản hoặc mật khẩu không chính xác !");
            }
            return View("Login");
        }
    }
}

Animals/Controllers/CreateUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver.Core;
using System.Configuration;
using Animals.App_Start;
using Animals.Models;
using MongoDB.Driver;
using System.Web.UI.WebControls;

namespace Animals.Controllers
{
    public class CreateUserController : Controller
    {
        private IMongoCollection<CreateUserModel> createUserCollection;
        private CreateUserConfig createUserConfig;
        public CreateUserController()
        {
            createUserConfig = new CreateUserConfig();
            createUserCollection = createUserConfig.database.GetCollection<CreateUserModel>("Craete");
        }
        // GET: CreateUser
        public ActionResult Index()
        {
            List<CreateUserModel> animals = createUserCollection.AsQueryable<CreateUserModel>().ToList();
            return View(animals);
        }

        // GET: CreateUser/Details/5
        public ActionResult Details(string id)
        {
            var UserId = new ObjectId(id);
            var User = createUserCollection.AsQueryable<CreateUserModel>().SingleOrDefault(x => x.id == UserId);
            return View(User);
        }

        // GET: CreateUser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CreateUser/Create
        [HttpPost]
        public ActionResult Create(CreateUserModel createUser)
        {
            try
            {
                // TODO: Add insert logic here

                createUserCollection.InsertOne(createUser);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CreateUser/Edit/5
        public ActionResult Edit(string id)
        {
            var UserId = new ObjectId(id);
            var User = createUserCollection.AsQueryable<CreateUserModel>().SingleOrDefault(x => x.id == UserId);
            return View(User);
        }

        // POST: CreateUser/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, CreateUserModel createUser)
        {
            try
            {
                // TODO: Add update logic here
                var filter = Builders<CreateUserModel>.Filter.Eq("_id", ObjectId.Parse(id));
                var update = Builders<CreateUserModel>.Update
                    .Set("UserName", createUser.UserName)
                    .Set("PassWord", createUser.PassWord)
                    .Set("Email", createUser.Email)
                    .Set("Phone", createUser.Phone)
                    .Set("Address", createUser.Address);
                var result = createUserCollection.UpdateOne(filter, update);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // GET: CreateUser/Delete/5
        public ActionResult Delete(string id)
        {
            var UserId = new ObjectId(id);
            var User = createUserCollection.AsQueryable<CreateUserModel>().SingleOrDefault(x => x.id == UserId);
            return View(User);
        }

        // POST: Animals/Delete/5
        [HttpPost]
        public ActionResult Delete(string id, CreateUserModel createUser)
        {
            try
            {
                // TODO: Add delete logic here
                createUserCollection.DeleteOne(Builders<CreateUserModel>.Filter.Eq("_id", ObjectId.Parse(id)));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Animals/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver.Core;
using System.Configuration;
using Animals.App_Start;
using Animals.Models;
using MongoDB.Driver;

namespace Animals.Controllers
{
    public class LoginController : Controller
    {
        static List<LoginModels> logins = new List<LoginModels>();
        public ActionResult Index()
        {
            return View(logins);
        }
        public ActionResult Record(LoginModels logins)
        {
            return View(logins);
        }
        public ActionResult Login()
        {
            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Login(LoginModels login)
        {
            if (!ModelState.IsValid)
            {
                return View("Login", login);
            }
            logins.Add(login);
            return RedirectToAction("Index");
        }
    }
}

Animals/Views/Animals/Create.cshtml
@model Animals.Models.AnimalsModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AnimalsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Animals/Views/Animals/Delete.cshtml
@model Animals.Models.AnimalsModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnimalsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Animals/Views/Animals/Details.cshtml
@model Animals.Models.AnimalsModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AnimalsModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Animals/Views/Animals/Edit.cshtml
@model Animals.Models.AnimalsModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AnimalsModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Animals/Views/Animals/Index.cshtml
@model IEnumerable<Animals.Models.AnimalsModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id =item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id})
        </td>
    </tr>
}

</table>

Animals/Views/Animals/Login.cshtml
@model Animals.Models.LoginModels

@{
    ViewBag.Title = "Login";
}

<html>
<head runat="server">
    <title>Login</title>
</head>
<body bgcolor="#ff80c0">
    <div>
        <h2>Login</h2>
        @Html.ValidationSummary("Create was unsuccessful. Please correct the errors and try again.")
        @using (Html.BeginForm())
        {
        <fieldset>
            <legend>Fields</legend>
            <p>
                <label for="UserName">UserName:</label>
               @Html.TextBox("UserName")
               @Html.ValidationMessage("Id", "*")
            </p>
            <p>
                <label for="Password">Password:</label>
                @Html.Password("*")
                @Html.ValidationMessage("Password", "*")
            </p>
            <p>
                <input type="submit" value="Login" />
            </p>
        </fieldset>
        }
        <div>
            @Html.ActionLink("Chưa có tài khoản, tạo mới", "Create", "CreateUser")
        </div>
    </div>
</body>
</html>

Animals/Views/Animals/Record.cshtml
@model Animals.Models.LoginModels

@{
    ViewBag.Title = "Record";
}

<html>
<head runat="server">
    <title>Record</title>
</head>
<body bgcolor="#ff80ff">
    <div>
        <h2>Details</h2>
        <fieldset>
            <legend>Display Fields</legend>
            <p>
                Username:
                @Html.Encode(Model.Username)
            </p>
            <p>
                Password:
                @Html.Encode(Model.Password)
            </p>
            <p>
                Email:
                @Html.Encode(Model.Email)
            </p>
        </fieldset>
        <p>
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</body>
</html>